name: myenv

channels:
 - astropy
 - conda-forge
 - defaults

dependencies:
 - setuptools
 - scipy
 - numpy
 - astropy>=4.0
 - matplotlib>3.1.0
 - swig
 - future
 - iminuit
 - corner
 - six
 - emcee
 - pytest